Login messages config
fastiuk/sonic-buildimage pull request #4
Opened 2022-07-02 19:44 UTC by fastiuk

#### Why I did it

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2022-07-02 20:15 UTC, fastiuk commented
@stepanblyschak please review

2022-07-04 09:14 UTC, stepanblyschak commented
@fastiuk What is the use case?

2022-07-04 15:27 UTC, fastiuk commented
> @fastiuk What is the use case?

The use case is to customize/rebrand your switch.
For example: here is a default Login screen:
<img width="833" alt="Screenshot 2022-07-04 at 18 05 24" src="https://user-images.githubusercontent.com/35844154/177180856-158a234b-7fec-4213-97c6-52b654d8e0a2.png">
After customizing it will look like this (or in any other way you want):
<img width="777" alt="Screenshot 2022-07-04 at 18 27 10" src="https://user-images.githubusercontent.com/35844154/177184020-c5f05825-dbd0-4761-ade9-792a067e217f.png">

2022-07-04 15:53 UTC, stepanblyschak commented
@fastiuk What is the use case for a user to customize this message through config db?
If you want to create an NVIDIA distribution of SONiC you can modify this file at image build time.

2022-07-05 15:26 UTC, fastiuk commented
> What is the use case for a user to customize this message through config db?
> If you want to create an NVIDIA distribution of SONiC you can modify this file at image build time.

The use case is to be able to configure it at runtime. It is not a good user experience if it needs to rebuild an image in order to change the login messages. From the user's perspective of view: the user will grab the prebuilt image from github/artifactory/etc install it and then configure it out-of-box without a need to rebuild it.

2022-07-05 16:07 UTC, stepanblyschak requested changes
Do not include submodule update in this PR. Submodule update should be done in a separate PR.

I understand the motivation to change the "welcome" message for custom images. AFAIK Alibaba, Kuaishu, etc. - those companies build their own distribution based on SONiC and they change the welcome message. That is nice, because when you enter the switch you know is SONiC based you see which company's distribution you are on as every company has own modifications to the image.

However, I do not understand the benefit of having this configurable though CONFIG DB and letting the user to configure it. What does user gain by doing so? This seems purelly cosmetic and can be done by editing files mannually by the user since SONiC gives you full access to the  filesystem. We will have to come up with an HLD with this proposal and review with community first before internal code review.

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-host-services/scripts/hostcfgd
> +    def login_message(self, key, data):
```suggestion
    def set_login_message(self, key, data):
```

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-host-services/scripts/hostcfgd
> +            return
Why type checks are needed ? ```isinstance``` and ```type```?

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-host-services/scripts/hostcfgd
> +            return
Is maintaining a cache really needed? Is the performance gains over cost of maintaining a valid cache in the code justified?

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-host-services/scripts/hostcfgd
> +                        True, True)
use explicit keyword arguments, like login_err=True to improve readability

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-host-services/scripts/hostcfgd
> +        syslog.syslog(f'Set new {key} message: {msg}')
What is the severity of this message? INFO, DEBUG?

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-yang-models/tests/files/sample_config_db.json
> -                 ],
Don't change these lines

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-yang-models/tests/files/sample_config_db.json
> +
Remove empty line

2022-07-05 16:07 UTC, stepanblyschak commented on src/sonic-yang-models/yang-models/sonic-login_message.yang
> +/* end of module nvue */
End of module sonic-login_message

2022-07-29 19:58 UTC, fastiuk commented on src/sonic-host-services/scripts/hostcfgd
> +        syslog.syslog(f'Set new {key} message: {msg}')
default for syslog is INFO

2022-07-29 19:59 UTC, fastiuk commented on src/sonic-host-services/scripts/hostcfgd
> +            return
I did the same as other "Cfg" classes do.

2022-07-29 20:01 UTC, fastiuk commented on src/sonic-host-services/scripts/hostcfgd
> +            return
to avoid unexpected fails.
If something bad will come from outside we will filter it here.

2022-07-29 20:14 UTC, fastiuk commented
Hostcfgd moved here: https://github.com/fastiuk/sonic-host-services/pull/1

2022-08-30 07:11 UTC, fastiuk commented
Hey @stepanblyschak . Can we create community PR for this?

2022-10-25 09:20 UTC, stepanblyschak approved these changes

2023-05-17 14:53 UTC, closed without merging