Firmware update control
fastiuk/sonic-buildimage pull request #5
Opened 2022-07-03 00:55 UTC by fastiuk

This PR depends on https://github.com/fastiuk/sonic-swss-common/pull/3

#### Why I did it
* Add an ability to control ASIC FW update
  * Ability to enable/disable FW update
  * Ability to choose FW source: image/user-defined

#### How to verify it
Build SONiC
or
When SONiC was already built:
```
rm -f target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl
BLDENV=bullseye make -f Makefile.work target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl
rm -f target/sonic-mellanox.bin
make target/sonic-mellanox.bin
```
Login into the switch.
Disable FW auto-update:
```
redis-cli -n 4 HSET "FIRMWARE|asic" "auto_update" "disable"
sudo reboot
```
See the results:
![Screenshot 2022-07-03 at 02 20 43](https://user-images.githubusercontent.com/35844154/177020334-66b0f9e3-4548-46e3-994c-34b9f89f38be.png)
Enable auto-update, change source to user-defined and copy FW image in place:
```
redis-cli -n 4 HSET "FIRMWARE|asic" "auto_update" "enable"
redis-cli -n 4 HSET "FIRMWARE|asic" "default" "user"
sudo mkdir -p /host/mlnx/asic/
sudo cp /tmp/fw-SIB2-rel-15_2010_1312-EVB.mfa /host/mlnx/asic/fw.mfa
sudo reboot
```
![Screenshot 2022-07-03 at 03 42 37](https://user-images.githubusercontent.com/35844154/177020394-2d7ee205-0d29-416d-a7ae-5ab91691efc6.png)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog
* Add an ability to control ASIC FW update

#### Link to config_db schema for YANG module changes
[sonic-login_message.yang](https://github.com/fastiuk/sonic-buildimage/tree/firmware-update-control/src/sonic-yang-models/yang-models/sonic-firmware.yang)

#### Submodules PR's :
| Repo  | PR title | State |
| ----------------- | ----------------- | ----------------- |
| sonic-swss-common | [Firmware update control](https://github.com/fastiuk/sonic-swss-common/pull/3) | ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/fastiuk/sonic-swss-common/3) |

#### A picture of a cute animal
![1-46](https://user-images.githubusercontent.com/35844154/169010699-e61cb22f-c9ae-4d12-8ef1-64e3607eef4c.jpeg)

2022-07-05 17:02 UTC, fastiuk commented
@stepanblyschak please review

2022-10-25 09:41 UTC, stepanblyschak requested changes
I wonder what is the real world use case for the end user. We know that we **must** have FW version and SDK version aligned. Without a mechanism to upgrade SDK and/or a mechanism to ensure user provided FW is guarateed to work with installed SDK version we create a possibility break the system easily.
If the intent is to allow user have a fix in new FW without waiting for the new SONiC image we can tell the user to replace the FW file under /etc and perform reboot to achive it.
I am also not sure why do we need to control "auto_update". We **must** upgrade FW prior to cold/fast/warm upgrade. If the user configuration disables it we should clearly let user know that these flows will be broken.

2022-10-25 09:41 UTC, stepanblyschak commented on files/build_templates/init_cfg.json.j2
> +{% endif %}
This design must be reviewed with community to cover all platforms and ASIC vendors. It is not easy to push something to configuration that was designed to work only with specific platforms

2022-10-25 09:41 UTC, stepanblyschak commented on src/sonic-yang-models/yang-models/sonic-firmware.yang
> +                    type auto-update;
Please add description for leafs

2022-10-25 09:41 UTC, stepanblyschak commented on src/sonic-yang-models/tests/files/sample_config_db.json
> +
Remove empty line

2022-10-25 10:16 UTC, fastiuk commented
> I wonder what is the real world use case for the end user.

It will allow users to control ASIC firmware and install their own images.

> We know that we **must** have FW version and SDK version aligned. Without a mechanism to upgrade SDK and/or a mechanism to ensure user provided FW is guarateed to work with installed SDK version we create a possibility break the system easily.

1. I am not sure we **must** have versions completely aligned. I think on some systems we can have a little deviation between versions at least minor ones.
2. We don't have that mechanism to guarantee that new FW will work with a current SDK, so it will be user-responsibility to use proper FW.

> If the intent is to allow user have a fix in new FW without waiting for the new SONiC image we can tell the user to replace the FW file under /etc and perform reboot to achive it.

We can but it is not a good user experience. In that case, the user will remove the old FW and won't be able to get it back (iow: it is not straightforward). That feature allows user to choose which FW to use.

> I am also not sure why do we need to control "auto_update". We **must** upgrade FW prior to cold/fast/warm upgrade. If the user configuration disables it we should clearly let user know that these flows will be broken.

That requirement came from another Nvidia OS which allows doing so. 
From user perspective it will allow user to install FW, but not install it right now. Only install when user enable auto-update.

2022-10-25 10:16 UTC, fastiuk commented on files/build_templates/init_cfg.json.j2
> +{% endif %}
Of course

2022-10-25 10:39 UTC, stepanblyschak commented on platform/mellanox/mlnx-fw-upgrade.j2
> +DEFAULT_SOURCE="$(sonic-cfggen -d -v FIRMWARE[\'asic\'][\'default\'])"
Also please make sure that we are able to perform reboot when database service is down or config db is not initialized

2022-10-25 10:40 UTC, stepanblyschak commented
> > I wonder what is the real world use case for the end user.
> 
> It will allow users to control ASIC firmware and install their own images.
> 
> > We know that we **must** have FW version and SDK version aligned. Without a mechanism to upgrade SDK and/or a mechanism to ensure user provided FW is guarateed to work with installed SDK version we create a possibility break the system easily.
> 
> 1. I am not sure we **must** have versions completely aligned. I think on some systems we can have a little deviation between versions at least minor ones.
> 2. We don't have that mechanism to guarantee that new FW will work with a current SDK, so it will be user-responsibility to use proper FW.
> 
> > If the intent is to allow user have a fix in new FW without waiting for the new SONiC image we can tell the user to replace the FW file under /etc and perform reboot to achive it.
> 
> We can but it is not a good user experience. In that case, the user will remove the old FW and won't be able to get it back (iow: it is not straightforward). That feature allows user to choose which FW to use.
> 
> > I am also not sure why do we need to control "auto_update". We **must** upgrade FW prior to cold/fast/warm upgrade. If the user configuration disables it we should clearly let user know that these flows will be broken.
> 
> That requirement came from another Nvidia OS which allows doing so. From user perspective it will allow user to install FW, but not install it right now. Only install when user enable auto-update.

@fastiuk I suggest to contact @nazariig and understand how this effort relates to [FW util](https://github.com/sonic-net/SONiC/blob/master/doc/fwutil/fwutil.md) and ask to review as he's the code owner for fw upgrade script.

I would also suggest to give a confirmation promt/warning to the user when he does warm/fast reboot when "auto_update" is disabled.

2023-03-21 18:37 UTC, closed without merging